version: '3.8'

services:
  findit-backend:
    build: .
    container_name: findit_backend
    restart: always
    ports:
      - "3335:3335" 
    volumes:
    - ./uploads:/app/uploads
    environment:
      - PORT=3335
      - DB_PORT=3306
      - DB_HOST=172.17.0.1
      - DB_USER=felipe
      - DB_PASSWORD=2007
      - DB_NAME=findit_db
      - JWT_SECRET_CODE=finditfinditfindit
    extra_hosts:
      - "host.docker.internal:host-gateway"



