version: '3.8'

services:
  findit-backend:
    volumes:
        - ./uploads:/app/uploads
    build: .
    container_name: findit_backend
    restart: always
    ports:
      - "3335:3335" 
    environment:
      - PORT=3335
      - DB_HOST=findit-db       
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=findit_db
    extra_hosts:
      - "host.docker.internal:host-gateway"